### ISSUE TITLE
DistrictHeatingNetwork_dp

### ISSUE THREAD

**Issue by PereiraUCD** [UdK-VPT/BuildingSystems#104]
Anyone who managed to get this example: DistrictHeatingNetwork_dp working, could give me a help? I keep getting this compilation error:

Compiler message:

Compiling and linking the model (GCC). 

dsmodel.c: In function 'equations_31':
dsmodel.c:11931:47: warning: passing argument 1 of 'StringTemporaryDense' from incompatible pointer type [-Wincompatible-pointer-types]
StringElement( StringTemporaryDense( &DYNX(DYNAuxStr_,26+DYNStrInit(did_)),
^
In file included from C:/Program Files (x86)/Dymola 2018/Source/matrixop.h:11:0,
from dsmodel.c:7:
C:/Program Files (x86)/Dymola 2018/Source/matrixop1.h:490:27: note: expected 'const char **' but argument is of type 'char **'
DYMOLA_STATIC StringArray StringTemporaryDense(String*d,SizeType ndims,...);
^~~~~~~~~~~~~~~~~~~~
dsmodel.c:12100:47: warning: passing argument 1 of 'StringTemporaryDense' from incompatible pointer type [-Wincompatible-pointer-types]
StringElement( StringTemporaryDense( &DYNX(DYNAuxStr_,45+DYNStrInit(did_)),
^
In file included from C:/Program Files (x86)/Dymola 2018/Source/matrixop.h:11:0,
from dsmodel.c:7:
C:/Program Files (x86)/Dymola 2018/Source/matrixop1.h:490:27: note: expected 'const char **' but argument is of type 'char **'
DYMOLA_STATIC StringArray StringTemporaryDense(String*d,SizeType ndims,...);
^~~~~~~~~~~~~~~~~~~~
dsmodel.c: In function 'equations_32':
dsmodel.c:12229:47: warning: passing argument 1 of 'StringTemporaryDense' from incompatible pointer type [-Wincompatible-pointer-types]
StringElement( StringTemporaryDense( &DYNX(DYNAuxStr_,7+DYNStrInit(did_)),
^
In file included from C:/Program Files (x86)/Dymola 2018/Source/matrixop.h:11:0,
from dsmodel.c:7:
C:/Program Files (x86)/Dymola 2018/Source/matrixop1.h:490:27: note: expected 'const char **' but argument is of type 'char **'
DYMOLA_STATIC StringArray StringTemporaryDense(String*d,SizeType ndims,...);
^~~~~~~~~~~~~~~~~~~~
dsmodel.c:12731:47: warning: passing argument 1 of 'StringTemporaryDense' from incompatible pointer type [-Wincompatible-pointer-types]
StringElement( StringTemporaryDense( &DYNX(DYNAuxStr_,7+DYNStrInit(did_)),
^
In file included from C:/Program Files (x86)/Dymola 2018/Source/matrixop.h:11:0,
from dsmodel.c:7:
C:/Program Files (x86)/Dymola 2018/Source/matrixop1.h:490:27: note: expected 'const char **' but argument is of type 'char **'
DYMOLA_STATIC StringArray StringTemporaryDense(String*d,SizeType ndims,...);
^~~~~~~~~~~~~~~~~~~~
dsmodel.c: In function 'equations_33':
dsmodel.c:13112:47: warning: passing argument 1 of 'StringTemporaryDense' from incompatible pointer type [-Wincompatible-pointer-types]
StringElement( StringTemporaryDense( &DYNX(DYNAuxStr_,45+DYNStrInit(did_)),
^
In file included from C:/Program Files (x86)/Dymola 2018/Source/matrixop.h:11:0,
from dsmodel.c:7:
C:/Program Files (x86)/Dymola 2018/Source/matrixop1.h:490:27: note: expected 'const char **' but argument is of type 'char **'
DYMOLA_STATIC StringArray StringTemporaryDense(String*d,SizeType ndims,...);
^~~~~~~~~~~~~~~~~~~~
dsmodel.c:13664:47: warning: passing argument 1 of 'StringTemporaryDense' from incompatible pointer type [-Wincompatible-pointer-types]
StringElement( StringTemporaryDense( &DYNX(DYNAuxStr_,26+DYNStrInit(did_)),
^
In file included from C:/Program Files (x86)/Dymola 2018/Source/matrixop.h:11:0,
from dsmodel.c:7:
C:/Program Files (x86)/Dymola 2018/Source/matrixop1.h:490:27: note: expected 'const char **' but argument is of type 'char **'
DYMOLA_STATIC StringArray StringTemporaryDense(String*d,SizeType ndims,...);
^~~~~~~~~~~~~~~~~~~~
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_createEasyVar1D]+0xa): undefined reference to `__security_cookie'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_createEasyVar1D]+0x2e): undefined reference to `nc_open'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_createEasyVar1D]+0x4a): undefined reference to `@__security_check_cookie@4'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_createEasyVar1D]+0x62): undefined reference to `nc_inq_varid'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_createEasyVar1D]+0x89): undefined reference to `nc_inq_varndims'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_createEasyVar1D]+0xb0): undefined reference to `nc_inq_vardimid'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_createEasyVar1D]+0xca): undefined reference to `nc_inq_dimname'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_createEasyVar1D]+0x136): undefined reference to `@__security_check_cookie@4'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_ncEasyGetScattered2D]+0xa): undefined reference to `__security_cookie'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_ncEasyGetScattered2D]+0xae): undefined reference to `@__security_check_cookie@4'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_ncEasyGetAttributeDouble]+0x11): undefined reference to `nc_open'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_ncEasyGetAttributeDouble]+0x4a): undefined reference to `nc_inq_varid'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_ncEasyGetAttributeDouble]+0x82): undefined reference to `nc_inq_att'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_ncEasyGetAttributeDouble]+0xa7): undefined reference to `nc_get_att_double'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_ncEasyGetAttributeDouble]+0xbd): undefined reference to `nc_close'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_ncEasyGetAttributeLong]+0x11): undefined reference to `nc_open'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_ncEasyGetAttributeLong]+0x49): undefined reference to `nc_inq_varid'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_ncEasyGetAttributeLong]+0x80): undefined reference to `nc_inq_att'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_ncEasyGetAttributeLong]+0xa5): undefined reference to `nc_get_att_long'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_ncEasyGetAttributeLong]+0xbb): undefined reference to `nc_close'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_ncEasyGetAttributeString]+0x11): undefined reference to `nc_open'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_ncEasyGetAttributeString]+0x49): undefined reference to `nc_inq_varid'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_ncEasyGetAttributeString]+0x81): undefined reference to `nc_inq_att'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_ncEasyGetAttributeString]+0xbe): undefined reference to `nc_get_att_text'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataReaderEA.obj):(.text[_ncEasyGetAttributeString]+0xdf): undefined reference to `nc_close'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncScattered2D.obj):(.text[_ncScattered2DNew]+0x11): undefined reference to `nc_open'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncScattered2D.obj):(.text[_ncScattered2DNew]+0x35): undefined reference to `nc_inq_varid'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncScattered2D.obj):(.text[_ncScattered2DNew]+0x53): undefined reference to `nc_inq_varndims'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncScattered2D.obj):(.text[_ncScattered2DNew]+0x77): undefined reference to `nc_inq_vardimid'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncScattered2D.obj):(.text[_ncScattered2DNew]+0x88): undefined reference to `nc_inq_dimlen'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncScattered2D.obj):(.text[_ncScattered2DNew]+0xa2): undefined reference to `nc_inq_dimlen'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncScattered2D.obj):(.text[_ncScattered2DNew]+0x168): undefined reference to `nc_get_var_double'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncScattered2D.obj):(.text[_ncScattered2DNew]+0x29a): undefined reference to `nc_close'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncScattered2D.obj):(.text[_ncScattered2DGet]+0x7): undefined reference to `__security_cookie'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncScattered2D.obj):(.text[_ncScattered2DGet]+0x73): undefined reference to `@__security_check_cookie@4'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataSet1D.obj):(.text[_ncDataSet1DNew]+0x13): undefined reference to `nc_open'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataSet1D.obj):(.text[_ncDataSet1DNew]+0x38): undefined reference to `nc_inq_varid'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataSet1D.obj):(.text[_ncDataSet1DNew]+0x56): undefined reference to `nc_inq_varndims'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataSet1D.obj):(.text[_ncDataSet1DNew]+0xe4): undefined reference to `nc_inq_vardimid'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataSet1D.obj):(.text[_ncDataSet1DNew]+0xf5): undefined reference to `nc_inq_dimlen'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataSet1D.obj):(.text[_ncDataSet1DNew]+0x33e): undefined reference to `nc_get_var_double'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataSet1D.obj):(.text[_ncDataSet1DNew]+0x37d): undefined reference to `nc_get_var1_double'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataSet1D.obj):(.text[_ncDataSet1DNew]+0x3a5): undefined reference to `nc_get_var1_double'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataSet1D.obj):(.text[_ncDataSet1DFree]+0x2b): undefined reference to `nc_close'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataSet1D.obj):(.text[_loadChunk]+0x79): undefined reference to `nc_get_vara_double'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataSet1D.obj):(.text[_ncDataSet1DGetItem]+0x26): undefined reference to `nc_get_var1_double'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataSet1D.obj):(.text[_ncDataSet1DSetOption]+0xa0): undefined reference to `nc_get_var1_double'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataSet1D.obj):(.text[_ncDataSet1DSetOption]+0xc7): undefined reference to `nc_get_var1_double'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataSet1D.obj):(.text[_ncDataSet1DDumpStatistics]+0xa): undefined reference to `__security_cookie'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataSet1D.obj):(.text[_ncDataSet1DDumpStatistics]+0x2a): undefined reference to `nc_inq_varname'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataSet1D.obj):(.text[_ncDataSet1DDumpStatistics]+0x128): undefined reference to `@__security_check_cookie@4'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncDataSet1D.obj):(.text[_ncDataSet1DDumpStatistics]+0x17d): undefined reference to `@__security_check_cookie@4'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncVar1D.obj):(.text[_ncVar1DNew]+0x16): undefined reference to `nc_inq_varid'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncVar1D.obj):(.text[_ncVar1DNew]+0x3a): undefined reference to `nc_inq_varndims'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncVar1D.obj):(.text[_ncVar1DNew]+0x5d): undefined reference to `nc_inq_vardimid'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncVar1D.obj):(.text[_ncVar1DNew]+0x6d): undefined reference to `nc_inq_dimlen'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncVar1D.obj):(.text[_ncVar1DNew]+0x247): undefined reference to `nc_get_var_double'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncVar1D.obj):(.text[_ncVar1DNew]+0x4a3): undefined reference to `nc_get_var1_double'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncVar1D.obj):(.text[_ncVar1DNew]+0x4ce): undefined reference to `nc_get_var1_double'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncVar1D.obj):(.text[_loadChunk]+0x7e): undefined reference to `nc_get_vara_double'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncVar1D.obj):(.text[_ncVar1DGetItem]+0x45): undefined reference to `nc_get_var1_double'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncVar1D.obj):(.text[_ncVar1DSetOption]+0x179): undefined reference to `nc_get_var1_double'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncVar1D.obj):(.text[_ncVar1DSetOption]+0x1a2): undefined reference to `nc_get_var1_double'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncVar1D.obj):(.text[_ncVar1DDumpStatistics]+0xa): undefined reference to `__security_cookie'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncVar1D.obj):(.text[_ncVar1DDumpStatistics]+0x2c): undefined reference to `nc_inq_varname'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncVar1D.obj):(.text[_ncVar1DDumpStatistics]+0x73): undefined reference to `nc_inq_varname'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncVar1D.obj):(.text[_ncVar1DDumpStatistics]+0x16b): undefined reference to `@__security_check_cookie@4'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/ncVar1D.obj):(.text[_ncVar1DDumpStatistics]+0x1e4): undefined reference to `@__security_check_cookie@4'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/Misc.obj):(.text[_ncError]+0x1b): undefined reference to `nc_strerror'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/Misc.obj):(.text[_ncGetAttributeDoubleDefault]+0x1e): undefined reference to `nc_inq_att'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/Misc.obj):(.text[_ncGetAttributeDoubleDefault]+0x41): undefined reference to `nc_get_att_double'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/Misc.obj):(.text[_ncGetAttributeLongDefault]+0x1e): undefined reference to `nc_inq_att'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/Misc.obj):(.text[_ncGetAttributeLongDefault]+0x41): undefined reference to `nc_get_att_long'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/Misc.obj):(.text[_ncGetAttributeTextDefault]+0x1d): undefined reference to `nc_inq_att'
C:/Users/Toshiba/Desktop/BuildingSystems-master/netCDF-DataReader/NcDataReader2/Resources/Library/win32\ncDataReader2.lib(ncDataReader2.dir/Release/Misc.obj):(.text[_ncGetAttributeTextDefault]+0x4b): undefined reference to `nc_get_att_text'
C:/Users/Toshiba/Desktop/BuildingSys

**Comment by thorade** [comment]
All examples have been tested and should work with Dymola 2018 and Visual Studio 2015 on Windows 10. Unfortuantely, the netCDF-DataReader does not work out of the box with GCC on Windows, see this issue:
https://github.com/tbeu/netCDF-DataReader/issues/11
It could be fixed by compiling a DLL with matching OS, compiler and bitness, but supplying DLLs for all combinations is a lot of work.
