### ISSUE TITLE
compilation fail in OpenModelica of PhotovoltaicCoolingSystem example

### ISSUE THREAD

**Issue by GlennCeusters** [UdK-VPT/BuildingSystems#151]
Hi Guys,

I've been trying to run the PhotovoltaicCoolingSystems example in the latest stable OpenModelica (1.14.1) but the compilation fails (using gcc). With the other, more simple, examples I experience no issues. Any idea what can be the problem? Many thanks for your help!

`<builtin>: recipe for target 'BuildingSystems.Applications.AirConditioningSystems.PhotovoltaicCoolingSystem_06inz.o' failed
mingw32-make: *** [BuildingSystems.Applications.AirConditioningSystems.PhotovoltaicCoolingSystem_06inz.o] Error 1
mingw32-make: *** Waiting for unfinished jobs....
mingw32-make: Leaving directory 'C:/Users/BEGLCEU/AppData/Local/Temp/OPENMO~1/OMEdit/BUILDI~2.PHO'
Compilation process failed. Exited with code 2.`

the error message is to long, so I've attached it as a file.
[compulation log.txt](https://github.com/UdK-VPT/BuildingSystems/files/4076427/compulation.log.txt)

**Comment by thorade** [comment]
Hi,
not an answer to your question, but you might be interested to also look at the other tickets with OpenModelica label:
https://github.com/UdK-VPT/BuildingSystems/labels/OpenModelica

**Comment by GlennCeusters** [comment]
> Hi,
> not an answer to your question, but you might be interested to also look at the other tickets with OpenModelica label:
> https://github.com/UdK-VPT/BuildingSystems/labels/OpenModelica
> 
> As mentioned in #81 OpenModelica runs continuous tests on the BuildingSystems library,
> so you can also see the compilation/simulation/error log online, search for the model name here:
> https://libraries.openmodelica.org/branches/master/BuildingSystems/BuildingSystems.html
> https://libraries.openmodelica.org/branches/newInst/BuildingSystems/BuildingSystems.html
> 
> As you mention gcc: Does it work with Visual Studio?

**Comment by GlennCeusters** [comment]
Hi and thanks for your reply,

First of, sorry for the closed and reopening - an honest miss click :)

As far as I can [tell](https://libraries.openmodelica.org/branches/v1.14/BuildingSystems/files/BuildingSystems_BuildingSystems.Applications.AirConditioningSystems.PhotovoltaicCoolingSystem.err) it should work.

I'm using MinGW.

**Comment by adrpo** [comment]
OpenModelica 1.14.1 has the new front-end on by default in OMEdit. It seems that is the issue.
You can select the old frontend via: Tools->Options->Simulation->Enable old frontend for code generation.

**Comment by GlennCeusters** [comment]
This solved the problem indeed (strange because usually we get a pop-up warning if this might be the issue, which I was not getting now).

Many thanks for your fast reply!
