### ISSUE TITLE
SolarRadiationTransformer models

### ISSUE THREAD

**Issue by carlesRT** [UdK-VPT/BuildingSystems#19]
The models in the `SolarRadiationTransformers` package can be improved.

<h6>
proposed changes
</h6>

- In `SolarRadiationTransformerGeneral`

---

Edited
~~1. Remove `Deg` and `Angle` of the name of the `cos..` and `sin..` variables such as `cosAngleDegInc`~~

There are some variables with the name `AngleDeg...`. So I guess it is not a good idea to change the names.

---
1. Change Type `BuildingSystems.Types.Angle_deg` per `Modelica.SIunits.Conversions.NonSIunits.Angle_deg` (It could be done per other models too). see 6b3da87
- `SolarRadiationTransformerIsotropic`
1. Add upper limit to the direct irradaition on a tilted surface (In some simulations the value of `IrrDirHor*R` is higher than the total irradiance on a tilted surface `IrrTotTil`, thus the diffuse irradiation on the tilted surface `radiationPort.IrrDif` becomes negative). See f397b20
2. Some changes in docu. See da1f359

**Comment by carlesRT** [comment]
Incident direct radiation on tilted surface `IrrDir`, is equal to `R * IrrDirHor`. The geometric factor `R=cosAngleDegInc/cosAngleZen` is wrong (That's why negative diffuse radiation was appear, etc.). I will correct it.

**Comment by nytschgeusen** [comment]
I think the equation for `R`  is in principle correct, but during extreme situations (during sunrise, sunset) in could calculate not plausible values. You will look for alternative modelling approaches as discussed.

**Comment by mlauster** [comment]
This might relevant in this context?
https://github.com/ibpsa/modelica/pull/625
https://github.com/ibpsa/modelica/issues/608

**Comment by carlesRT** [comment]
Thanks @mlauster. Yep  these are the same problems. 
@nytschgeusen  you are right, equation `R` is correct. Regarding the irradation on a tilted surface: Direct irradiation increases too much, because of the R-issue you mentioned, even over the solar constant value. The total irradiation is limited to the solar constant which yields negative diffuse irradiation...

In annex60 the normal direct radiation (it corresponds to our `IrrDirHor/cosAngleZen`) is limited to the solar constant ` 1367.7 W/m2`. Since `cosAngleDegInc <= 1` it is hardly to expect neither too high values for the direct irradiaiton nor negative diffuse radiation in the annex60 model. Besides, diffuse radiation is independently calculated, so that I think that if a problem occurs it would be a total irradiation greater than the solar constant rather than negative diffuse irradiation.

Anyway we might want to adapt the same approach. We might also want to limit the direct radiation on a tilted surface to a value equal to the solar constant - diffuse radation. @nytschgeusen ?

**Comment by nytschgeusen** [comment]
Issue #19 solved
