### ISSUE TITLE
German comments

### ISSUE THREAD

**Issue by thorade** [UdK-VPT/BuildingSystems#2]
There are some comments in German that should be translated or removed or moved into a proper documentation. Search for:
 - [x] [derzeit](https://github.com/UdK-VPT/BuildingSystems/search?type=Code&utf8=%E2%9C%93&q=derzeit)
 - [x] [alte](https://github.com/UdK-VPT/BuildingSystems/search?type=Code&utf8=%E2%9C%93&q=alte)
 - [x] [Waende](https://github.com/UdK-VPT/BuildingSystems/search?type=Code&utf8=%E2%9C%93&q=Waende)
 - [x] [Netto](https://github.com/UdK-VPT/BuildingSystems/search?type=Code&utf8=%E2%9C%93&q=Netto)
 - [x] [brutto](https://github.com/UdK-VPT/BuildingSystems/search?type=Code&utf8=%E2%9C%93&q=brutto)
 - [x] [davon](https://github.com/UdK-VPT/BuildingSystems/search?type=Code&utf8=%E2%9C%93&q=davon)
 - [x] [Kennlinien](https://github.com/UdK-VPT/BuildingSystems/search?type=Code&utf8=%E2%9C%93&q=Kennlinien)
 - [x] [ausgehend](https://github.com/UdK-VPT/BuildingSystems/search?type=Code&utf8=%E2%9C%93&q=ausgehend)
 - [x] [Abhaengigkeit ](https://github.com/UdK-VPT/BuildingSystems/search?type=Code&utf8=%E2%9C%93&q=Abhaengigkeit)
 - [x] [Gueltigkeitsbereich](https://github.com/UdK-VPT/BuildingSystems/search?type=Code&utf8=%E2%9C%93&q=Gueltigkeitsbereich)
 - [x] [Luft](https://github.com/UdK-VPT/BuildingSystems/search?type=Code&utf8=%E2%9C%93&q=Luft)
 - [x] [Enthalpie](https://github.com/UdK-VPT/BuildingSystems/search?type=Code&utf8=%E2%9C%93&q=Enthalpie)
 - [x] Druck
 - [x] Dampf
 - [x] Saettigung
 - [x] und
 - [x] ist
 - [x] ä
 - [x] ü
 - [x] ö

To be continued...

**Comment by jmoeckel** [comment]
Extended the list by some typical words and language-specific letters.
