### ISSUE TITLE
Wrong temperature at heatPort in zone model

### ISSUE THREAD

**Issue by carlesRT** [UdK-VPT/BuildingSystems#30]
The temperature of the outter interface `heatSourcesPorts` of the zone model `zoneTemplateAirvolumeMixed` is constant and equal to 20 °C. 

This information/temperature is then forwarded to the outter interface of the building models `heatSourcesPorts[nHeatSources]` and used to connect external heating or cooling installations (`BuildingSystems.Applications.HeatingSystems.WaterHeatingSystem`, ...)

The temperature is set with `heatPort.T = 293.15;` in the model `BuildingSystems.Buildings.BaseClasses.RelationRadiationConvection` 

To solve it, it should be first decided which temperature should be linked to the `heatPort` 

* Indoor air temperature in zone ? Then, set `heatPort.T =  heatPortCv.T ; `
* Mean temperature of the in room surfaces ? Then, set `heatPort.T = heatPortLw.T ; `

**Comment by nytschgeusen** [comment]
Problem is solved by an introduction of a further heat port. The building model and the zone model have now two different heat ports, one fpr convective heat sources and one for radiative heat sources
