### ISSUE TITLE
Non pedantic error in `Technologies.Photovoltaics.BaseClasses.ElectricalModels.ElectricalModelTwoDiodesGeneral`

### ISSUE THREAD

**Issue by jmoeckel** [UdK-VPT/BuildingSystems#35]
Error is thrown in standard check mode (so not `pedantic`):
To reproduce, use
`checkModel("BuildingSystems.Technologies.Photovoltaics.BaseClasses.ElectricalModels.ElectricalModelTwoDiodesGeneral")`

**Comment by thorade** [comment]
Should be covered by #21

**Comment by nytschgeusen** [comment]
bug is fixed, because its now a partial model
