### ISSUE TITLE
Non pedantic error `Buildings.Zones.ZoneTemplateAirvolume3D`

### ISSUE THREAD

**Issue by jmoeckel** [UdK-VPT/BuildingSystems#36]
Error is thrown in standard check mode (so not `pedantic`):
To reproduce, use
`checkModel("BuildingSystems.Buildings.Zones.ZoneTemplateAirvolume3D")`

There also errors thrown by:
- [ ] `BuildingSystems.Buildings.Zones.Examples.SingleZoneThermal3D`
- [ ] `BuildingSystems.Buildings.Examples.ThermalModelHouse3D`
- [ ] `BuildingSystems.Buildings.Examples.ThermalModelHouse3Dwindow`

but I think, because of `extends`, they all based on the error in the zone.

**Comment by kmucha** [comment]
Taken note of this errors! I think this errors are linked to the familiar connector-structure problem of ZoneTemplateGeneral - so I'm awaiting a trend-setting decision!

> but I think, because of extents, they all based on the error in the zone
true!

**Comment by jmoeckel** [comment]
Closing this issue with as it will be handled by #65
