### ISSUE TITLE
Error in ``Buildings.Data.AirpathCharacteristics.CdTiltedPane``

### ISSUE THREAD

**Issue by jmoeckel** [UdK-VPT/BuildingSystems#66]
Applying Dymolas (2017 FD01) ``checkModel()`` in pedantic mode to ``Buildings.Data.AirpathCharacteristics.CdTiltedPane`` throws following error:

````
Component type specifier Angle_degInput is a connector, that should not be used in a function
File: Q:/Git/BuildingSystems/BuildingSystems/Buildings/Data/AirpathCharacteristics/CdTiltedPane.mo, line 7
Component context: angleDegPanes
Component declared as Angle_degInput angleDegPanes in BuildingSystems.Interfaces

**Comment by nytschgeusen** [comment]
Problem solved by type substitution (Modelica.):

old version:  input BuildingSystems.Interfaces.Angle_degInput angleDegPanes;
new version:  input Modelica.SIunits.Conversions.NonSIunits.Angle_deg angleDegPanes;
