### ISSUE TITLE
Add campus models of TU Berlin

### ISSUE THREAD

**Issue by nytschgeusen** [UdK-VPT/BuildingSystems#74]
Add two district models to package BuildingSystems.Applications.DistrictSimulation

`UniversityCampusBerlinCharlottenburg.mo`

-> district model with low order building buildings of the university campus Berlin-Charlottenburg

`UniversityCampusBerlinCharlottenburgDistrictHeating.mo`

-> as `UniversityCampusBerlinCharlottenburg.mo`, but the building models are supplied by a district heating grid with thermal energy.

**Comment by ainderfurth** [comment]
See branch 'HCBC' for new files.
