### ISSUE TITLE
Moving Tipps and Tricks to Wiki

### ISSUE THREAD

**Issue by jmoeckel** [UdK-VPT/BuildingSystems#8]
Content of issues which contain valuable information, that should not be hard to find after closing the issue (as #3) should be moved to a new wiki-section (e.g. Tipps and Tricks). 

Do you think, that this is a good idea - or would it even makes things worse, as the wiki is the last place, where people look for information?

**Comment by ainderfurth** [comment]
Thumbs up!

**Comment by thorade** [comment]
@ainderfurth Did you mean :+1: ??

**Comment by thorade** [comment]
Another good place to "store" such information is to ask a question on stackoverflow. 
Does not fit for all examples, but some of them.

**Comment by thorade** [comment]
Should we add some useful links, too?
https://github.com/blog/967-github-secrets
https://github.com/tiimgreen/github-cheat-sheet
http://www.emoji-cheat-sheet.com/

**Comment by jmoeckel** [comment]
:+1: 

One page could be `Useful Links`.
  
The other referenced issues could be rewritten or summarized to short, single page articles.

The stackoverflow-idea is ok for me - definately would reach a much bigger audience. But I would follow the idea with the wiki pages as well. My idea is, that this repository could work as a standalone "application", meaning: Giving the user all informations that we think a relevant.

**Comment by jmoeckel** [comment]
Corresponding Wiki-Page(s) have been added. 
Further disucssion regarding single topics should be discussed somewhere else.
Closing this issue.
