### ISSUE TITLE
BSD-3-Clause

### ISSUE THREAD

**Issue by thorade** [UdK-VPT/BuildingSystems#82]
The Modelica Association seems to be switching to the BSD-3-Clause license (instead of Modelica license) for the Modelica Standard Library:
https://github.com/modelica/Modelica/issues/2320
https://github.com/modelica/Modelica/pull/2373
Once that is completed and released, we should consider switching to BSD-3-Clause as well.

https://choosealicense.com/licenses/bsd-3-clause/
https://opensource.org/licenses/alphabetical

**Comment by raulrpearson** [comment]
When choosing a license for my Modelica library, I found @dietmarw's and @mtiller's [Where impact got Going](https://github.com/impact/impact/blob/master/resources/docs/modelica2015/paper/impact.md#which-license-is-best-for-your-library) helpful.

> So what should the library developer do? The simplest solution is to not use the “Modelica License Version 2.0” for libraries but rather go for standard licenses that are more compatible with open source, community driven development (e.g., MIT or BSD licenses). Interestingly, the old “Modelica License Version 1.1” is still suitable for user libraries since it does not contain the restrictions of having to change the package name.

**Comment by dietmarw** [comment]
Just some update. The Modelica Association has just agreed (voted on) to move away from the custom Modelica License 2 and will be using BSD 3-clause in future for all its projects.

**Comment by thorade** [comment]
@raulrpearson Thanks. Also, one can find a lot of related issues here on github:
https://github.com/search?q=license+language%3Amodelica&type=Issues&utf8=%E2%9C%93

**Comment by thorade** [comment]
The MSL is now licensed under BSD-3
https://github.com/modelica/Modelica/issues/2320

**Comment by thorade** [comment]
MSL and IBPSA are now under BSD3,
so that we can also switch any time now.
