### ISSUE TITLE
clean up HAM/ConvectiveHeatTransfer/Gaps

### ISSUE THREAD

**Issue by thorade** [UdK-VPT/BuildingSystems#9]
Do we need to keep these functions?
- [BuildingSystems/HAM/ConvectiveHeatTransfer/Gaps/ny.mo](https://github.com/UdK-VPT/BuildingSystems/blob/master/BuildingSystems/HAM/ConvectiveHeatTransfer/Gaps/ny.mo)
- [BuildingSystems/HAM/ConvectiveHeatTransfer/Gaps/lambda.mo](https://github.com/UdK-VPT/BuildingSystems/blob/master/BuildingSystems/HAM/ConvectiveHeatTransfer/Gaps/lambda.mo)
- [BuildingSystems/HAM/ConvectiveHeatTransfer/Gaps/Pr.mo](https://github.com/UdK-VPT/BuildingSystems/blob/master/BuildingSystems/HAM/ConvectiveHeatTransfer/Gaps/Pr.mo)

...to be extended

**Comment by thorade** [comment]
Remove comments in lines 4-5 of 
https://github.com/UdK-VPT/BuildingSystems/blob/master/BuildingSystems/HAM/ConvectiveHeatTransfer/Gaps/package.mo#L4-L5
because they break the package.order refactoring of BuildingsPy

**Comment by nytschgeusen** [comment]
Function ny, lambda and Pr are used from function alphaGap. An new example BuildingSystems.HAM.ConvectiveHeatTransfer.Examples.AlphaGap demonstrates the application of this fucntion.
